name: Run cypress at 7am every day

on: pull-requests

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: /home/runner/work/ubuntu.com/ubuntu.com/run
          wait-on: 'http://0.0.0.0:8001/_status/check'
          wait-on-timeout: 180
          browser: chrome
          config-file: tests/cypress/cypress.json
          config: baseUrl=http://0.0.0.0:8001
      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=%23webteam
